version: '3.8'

services:
  port-builder:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_YXdha2Utc2hlZXAtNTAuY2xlcmsuYWNjb3VudHMuZGV2JA
        CLERK_SECRET_KEY: sk_test_sqicHuompwDD7nMT4yEiPPhdbetRNeNuLJ4rQX0dOv
        NEXT_PUBLIC_RAZORPAY_KEY_ID: rzp_live_vuatb495o1kgec
        NEXT_PUBLIC_URL: http://localhost:3000
    container_name: port-builder
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=pk_test_YXdha2Utc2hlZXAtNTAuY2xlcmsuYWNjb3VudHMuZGV2JA
      - CLERK_SECRET_KEY=sk_test_sqicHuompwDD7nMT4yEiPPhdbetRNeNuLJ4rQX0dOv
      - NEXT_PUBLIC_RAZORPAY_KEY_ID=rzp_live_vuatb495o1kgec
      - RAZORPAY_KEY_SECRET=Lh8f7HMBEBU2UGPsF6Te9Mho
      - RAZORPAY_WEBHOOK_SECRET=Gq@nZKDJ4pR2J9E
      - GITHUB_CLIENT_ID=Ov23li6LGx057XJUKucU
      - GITHUB_CLIENT_SECRET=2337ba7b3da8233f35d81bcfaa5a58914f15658c
      - NEXT_PUBLIC_GITHUB_CLIENT_ID=Ov23li6LGx057XJUKucU
      - VERCEL_CLIENT_ID=oac_cf4Ld2eVMfQ92BiHodVIcgYL
      - VERCEL_CLIENT_SECRET=dfHcH4d6VoHlMPAsd5vcHSR2
      - NEXT_PUBLIC_URL=http://localhost:3000
